### ISSUE TITLE
Feature request: command to validate if something is a semver

### ISSUE THREAD

**Issue by mymasse** [fsaintjacques/semver-tool#61]
We use a combination of the semver diff and bump to increment our docker images version based on included librairies in the docker file. However some of these libs don't use semver and we had to resort to a small hack. Having a command to check if something is a valid semver would be usefull.

Here is a snippet of what we are doing

```
set +e
semver get major ${CURRENT_APP_VERSION} >/dev/null 2>&1
IS_SEMVER=$?
set -e

if [[ ${IS_SEMVER} -eq 0 ]]; then
  NEW_IMAGE_VERSION=$(semver bump $(semver diff ${CURRENT_APP_VERSION} ${NEW_APP_VERSION}) ${CURRENT_IMAGE_VERSION})
else
  NEW_IMAGE_VERSION=$(semver bump major ${CURRENT_IMAGE_VERSION})
fi
```

What I would be looking at is removing the first 4 lines and basically using something like this instead

```
if [[ $(semver isvalid ${CURRENT_APP_VERSION}) -eq 0 ]]; then
  NEW_IMAGE_VERSION=$(semver bump $(semver diff ${CURRENT_APP_VERSION} ${NEW_APP_VERSION}) ${CURRENT_IMAGE_VERSION})
else
  NEW_IMAGE_VERSION=$(semver bump major ${CURRENT_IMAGE_VERSION})
fi
```

**Comment by fsaintjacques** [comment]
If you open a PR, I'll accept it since I think it improves readability. It shouldn't be too hard to implement. I would name the command `validate`, e.g. `semver validate $version`. I wouldn't use stdout for transmitting success, simply exit 0 if it's valid, 1 otherwise.

On this subject, the example can be simplified. You don't need the `set +e / set -e` guards and temporary variable, instead you can do the following:

```
if semver get major ${CURRENT_APP_VERSION} >/dev/null 2>&1; then
  ...
fi
```

The `if` operator in bash will swallow the return code of the command without aborting the execution of the script due to `set -e`.

**Comment by mymasse** [comment]
I'll see if I have to make a PR over the holidays.

And thanks for the simplification of my bash snippet until we have the new command!
