### ISSUE TITLE
Dots are not allowed in prerelease identifiers 

### ISSUE THREAD

**Issue by multicolaure** [fsaintjacques/semver-tool#77]
Dots are not considered as valid in the prelease part:

```
> semver validate 3.2.0-2023.03.03.1
invalid
```
without the dots: 
```
> semver validate 3.2.0-2301011
valid
```

Semver allows it:

> A pre-release version MAY be denoted by appending a hyphen and a series of **dot separated** identifiers immediately following the patch version

**Comment by ah-clem** [comment]
I believe that `semver` is behaving correctly.  It declares the version invalid not because of the dot separated identifiers, but because one or more of the numeric parts has a leading zero.
```
$ semver validate 3.2.0-2023.03.03.1
invalid
$ semver validate 3.2.0-2023.3.3.1
valid
```
From [semver.org](https://semver.org/):
```
A pre-release version MAY be denoted by appending a hyphen and a series of dot separated
identifiers immediately following the patch version. Identifiers MUST comprise only ASCII
alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric
identifiers MUST NOT include leading zeroes. 
```
It might be nice to have a better return value (in a verbose mode?) that explains why a version is considered invalid.  However, `semver` is really meant for scripting, not diagnostics.  As well, if anyone is going to start using semantic versions to manage data, one should really be familiar with the spec.  It's not that long or difficult to read .. and "so obvious" that many people don't read it carefully and are surprised at some of the rules when they *do* read it.  Ha!  Early versions of `semver` has such bugs!

**Comment by ranger6** [comment]
No bug here!
